// Generated by https://quicktype.io

export interface LocationsResult {
  results: Result[];
}

export interface LocationsApi {
  count: number;
  next: string;
  previous?: string;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
}
