// Generated by https://quicktype.io

export interface PokemonInfo {
  name: string;
  id: string;
  imgSrc: string;
}

export interface PokemonsResponse {
  results: PokemonInfo[];
}
export interface Pokemons {
  results: Result[];
}

export interface Result {
  national_number: string;
  evolution?: Evolution;
  sprites: Sprites;
  name: string;
  type: Type[];
  total: number;
  hp: number;
  attack: number;
  defense: number;
  sp_atk: number;
  sp_def: number;
  speed: number;
}

export interface Evolution {
  name: string;
}

export interface Sprites {
  normal: string;
  large: string;
  animated: string;
}

export enum Type {
  Bug = "Bug",
  Dark = "Dark",
  Dragon = "Dragon",
  Electric = "Electric",
  Fairy = "Fairy",
  Fighting = "Fighting",
  Fire = "Fire",
  Flying = "Flying",
  Ghost = "Ghost",
  Grass = "Grass",
  Ground = "Ground",
  Ice = "Ice",
  Normal = "Normal",
  Poison = "Poison",
  Psychic = "Psychic",
  Rock = "Rock",
  Steel = "Steel",
  Water = "Water",
}
